package com.dening.study.api.mybatis.dao.model;

import java.util.Date;
import lombok.Builder;
import lombok.Data;

/**
 * Database Table Remarks:
 *   测试人员表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table test_person
 */
@Data
@Builder
public class TestPerson {
    /**
     * Database Column Remarks:
     *   自增主健
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   姓氏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * Database Column Remarks:
     *   名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   身份证唯一编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.id_num
     *
     * @mbg.generated
     */
    private String idNum;

    /**
     * Database Column Remarks:
     *   出生时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.birth_time
     *
     * @mbg.generated
     */
    private Date birthTime;

    /**
     * Database Column Remarks:
     *   工作状态,0:未入职 1:已入职未入场 2:已入职入场 3:离职
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.work_status
     *
     * @mbg.generated
     */
    private Integer workStatus;

    /**
     * Database Column Remarks:
     *   软删除,0:未删除 1:已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.is_del
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   更新时间,单位秒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.create_time
     *
     * @mbg.generated
     */
    private Integer createTime;

    /**
     * Database Column Remarks:
     *   出生时间,单位秒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_person.update_time
     *
     * @mbg.generated
     */
    private Integer updateTime;
}