package com.dening.study.api.mybatis.dao;

import com.dening.study.api.mybatis.dao.model.TestPerson;

public interface TestPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_person
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_person
     *
     * @mbg.generated
     */
    int insert(TestPerson row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_person
     *
     * @mbg.generated
     */
    int insertSelective(TestPerson row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_person
     *
     * @mbg.generated
     */
    TestPerson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_person
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestPerson row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_person
     *
     * @mbg.generated
     *
     */
    int updateByPrimaryKey(TestPerson row);
}